### ISSUE TITLE
vue-tsc errors keep Unit Tests / Lint red after the eslint fix (#24 regression + test helper)

### ISSUE THREAD

**Issue by dzackgarza** [dzackgarza/zettlr-pandoc#29]
CI `Unit Tests / Lint` runs `yarn lint` = `yarn lint:code && yarn lint:types` (`.github/workflows/check.yml`). #25 cleared the eslint side (0 errors), but `yarn lint:types` (`vue-tsc --noEmit`) reports two errors, so the check stays red.

## The two errors

```
source/common/modules/markdown-editor/renderers/base-renderer.ts(71,32): error TS2554: Expected 3 arguments, but got 2.
test/editor-pandoc-div-widget.spec.ts(80,58): error TS2339: Property 'extensions' does not exist on type 'EditorStateConfig | undefined'.
```

### 1. `base-renderer.ts:71` — introduced by #24

`LineStyleResetWidget.updateDOM` calls `this.inner.updateDOM(dom, view)`; the installed `@codemirror/view` `WidgetType.updateDOM` type expects a different arity. Introduced by #24 (commit `0c28dfb0`, "one shared line-style reset for widgets and wrappers"). #24's Lint check was red and was dispositioned entirely as the pre-existing 23 eslint errors (#25); this vue-tsc regression was not separately accounted for.

### 2. `editor-pandoc-div-widget.spec.ts:80` — test helper

`createEditor`'s `extensions` param types `Parameters<typeof EditorState.create>[0]['extensions']`, but `[0]` is `EditorStateConfig | undefined`. Pre-existing test-helper type error.

## Why filed separately

Both live in files that the `infra/green-ci-and-normalization` fork (#25/#4/#26, PR #28) does not touch. Per the working guidance to fix only files that diverged from the base in the fork, they were left untouched there and tracked here instead. Fixing them is required for `Unit Tests / Lint` to actually go green.

## Acceptance

- `yarn lint:types` (`vue-tsc --noEmit`) reports 0 errors.
- `base-renderer.ts` fix is a real correction of the `updateDOM` call/override against the installed `@codemirror/view` API, not an `@ts-expect-error` or a widened `any`.
- The test helper is typed correctly without weakening what the spec asserts.
